#ifndef GRID_HEADER_DEFINE_H
#define GRID_HEADER_DEFINE_H


//项目管理
#pragma region ProjectManager						
#define IDX_PROJMGR_SEQ								0
#define IDX_PROJMGR_NAME							1
#define IDX_PROJMGR_TYPE							2
#define IDX_PROJMGR_MOLD							3
#define IDX_PROJMGR_DIAMETER						4
#define IDX_PROJMGR_SPECIFICATION					5
#define IDX_PROJMGR_CUSTOMERNAE						6
#define IDX_PROJMGR_USEPLACE						7
#define IDX_PROJMGR_DELIVERYPLACE					8
#define IDX_PROJMGR_STARTDATE						9
#define IDX_PROJMGR_COMPLETEDATE					10
#define IDX_PROJMGR_ADJUSTDATE						11
#define IDX_PROJMGR_PLANCHECKDATE					12
#define IDX_PROJMGR_REALCHECKDATE					13
#define IDX_PROJMGR_REALOUTDATE						14
#define IDX_PROJMGR_MANAGER							15
#define IDX_PROJMGR_PROJCHARGE						16
#define IDX_PROJMGR_QUALITYCHARGE					17
#define IDX_PROJMGR_CUTTERUNIT						18
#define IDX_PROJMGR_BODYUNIT						19
#define IDX_PROJMGR_PREASSEMBLY						20
#define IDX_PROJMGR_ASSEMBLYLOCATION				21
#define IDX_PROJMGR_CONTRACTINCOME					22
#define IDX_PROJMGR_SPLICE							23
#define IDX_PROJMGR_DRIVETYPE						24
#define IDX_PROJMGR_WORKSTATE						25
#define IDX_PROJMGR_CREATOR							26
#define IDX_PROJMGR_CREATETIME						27
#pragma endregion


#endif